name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests and Generate Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with HTML report
      run: |
        pytest -vv --html=test-report.html --self-contained-html

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-report.html
        retention-days: 30

  deploy:
    name: Upload Code Artifact
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload source code
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: |
          src/
          tests/
          requirements.txt
        retention-days: 30